#include <asm/io.h>
#include <linux/init.h>
#include <linux/input.h>
#include <linux/interrupt.h>
#include <linux/module.h>
#include <linux/printk.h>
#include <linux/tty.h>
#include <linux/tty_flip.h>
#include <linux/vt_kern.h>

#ifndef KEYB_IRQ
# define KEYB_IRQ 1
#endif

#ifndef DEV_NAME
# define DEV_NAME "ft_keyb"
#endif

// [MAP_START]
/* AUTO-GENERATED TABLES */
static const unsigned short ft_scancodes_std[256] = {
    [0] = KEY_RESERVED,
    [1] = KEY_ESC,
    [2] = KEY_1,
    [3] = KEY_2,
    [4] = KEY_3,
    [5] = KEY_4,
    [6] = KEY_5,
    [7] = KEY_6,
    [8] = KEY_7,
    [9] = KEY_8,
    [10] = KEY_9,
    [11] = KEY_0,
    [12] = KEY_MINUS,
    [13] = KEY_EQUAL,
    [14] = KEY_BACKSPACE,
    [15] = KEY_TAB,
    [16] = KEY_Q,
    [17] = KEY_W,
    [18] = KEY_E,
    [19] = KEY_R,
    [20] = KEY_T,
    [21] = KEY_Y,
    [22] = KEY_U,
    [23] = KEY_I,
    [24] = KEY_O,
    [25] = KEY_P,
    [26] = KEY_LEFTBRACE,
    [27] = KEY_RIGHTBRACE,
    [28] = KEY_ENTER,
    [29] = KEY_LEFTCTRL,
    [30] = KEY_A,
    [31] = KEY_S,
    [32] = KEY_D,
    [33] = KEY_F,
    [34] = KEY_G,
    [35] = KEY_H,
    [36] = KEY_J,
    [37] = KEY_K,
    [38] = KEY_L,
    [39] = KEY_SEMICOLON,
    [40] = KEY_APOSTROPHE,
    [41] = KEY_GRAVE,
    [42] = KEY_LEFTSHIFT,
    [43] = KEY_BACKSLASH,
    [44] = KEY_Z,
    [45] = KEY_X,
    [46] = KEY_C,
    [47] = KEY_V,
    [48] = KEY_B,
    [49] = KEY_N,
    [50] = KEY_M,
    [51] = KEY_COMMA,
    [52] = KEY_DOT,
    [53] = KEY_SLASH,
    [54] = KEY_RIGHTSHIFT,
    [55] = KEY_KPASTERISK,
    [56] = KEY_LEFTALT,
    [57] = KEY_SPACE,
    [58] = KEY_CAPSLOCK,
    [59] = KEY_F1,
    [60] = KEY_F2,
    [61] = KEY_F3,
    [62] = KEY_F4,
    [63] = KEY_F5,
    [64] = KEY_F6,
    [65] = KEY_F7,
    [66] = KEY_F8,
    [67] = KEY_F9,
    [68] = KEY_F10,
    [69] = KEY_NUMLOCK,
    [70] = KEY_SCROLLLOCK,
    [71] = KEY_KP7,
    [72] = KEY_KP8,
    [73] = KEY_KP9,
    [74] = KEY_KPMINUS,
    [75] = KEY_KP4,
    [76] = KEY_KP5,
    [77] = KEY_KP6,
    [78] = KEY_KPPLUS,
    [79] = KEY_KP1,
    [80] = KEY_KP2,
    [81] = KEY_KP3,
    [82] = KEY_KP0,
    [83] = KEY_KPDOT,
    [84] = KEY_RESERVED,
    [85] = KEY_RESERVED,
    [86] = KEY_RESERVED,
    [87] = KEY_F11,
    [88] = KEY_F12,
    [89] = KEY_RESERVED,
    [90] = KEY_RESERVED,
    [91] = KEY_RESERVED,
    [92] = KEY_RESERVED,
    [93] = KEY_RESERVED,
    [94] = KEY_RESERVED,
    [95] = KEY_RESERVED,
    [96] = KEY_RESERVED,
    [97] = KEY_RESERVED,
    [98] = KEY_RESERVED,
    [99] = KEY_RESERVED,
    [100] = KEY_RESERVED,
    [101] = KEY_RESERVED,
    [102] = KEY_RESERVED,
    [103] = KEY_RESERVED,
    [104] = KEY_RESERVED,
    [105] = KEY_RESERVED,
    [106] = KEY_RESERVED,
    [107] = KEY_RESERVED,
    [108] = KEY_RESERVED,
    [109] = KEY_RESERVED,
    [110] = KEY_RESERVED,
    [111] = KEY_RESERVED,
    [112] = KEY_RESERVED,
    [113] = KEY_RESERVED,
    [114] = KEY_RESERVED,
    [115] = KEY_RESERVED,
    [116] = KEY_RESERVED,
    [117] = KEY_RESERVED,
    [118] = KEY_RESERVED,
    [119] = KEY_RESERVED,
    [120] = KEY_RESERVED,
    [121] = KEY_RESERVED,
    [122] = KEY_RESERVED,
    [123] = KEY_RESERVED,
    [124] = KEY_RESERVED,
    [125] = KEY_RESERVED,
    [126] = KEY_RESERVED,
    [127] = KEY_RESERVED,
    [128] = KEY_RESERVED,
    [129] = KEY_RESERVED,
    [130] = KEY_RESERVED,
    [131] = KEY_RESERVED,
    [132] = KEY_RESERVED,
    [133] = KEY_RESERVED,
    [134] = KEY_RESERVED,
    [135] = KEY_RESERVED,
    [136] = KEY_RESERVED,
    [137] = KEY_RESERVED,
    [138] = KEY_RESERVED,
    [139] = KEY_RESERVED,
    [140] = KEY_RESERVED,
    [141] = KEY_RESERVED,
    [142] = KEY_RESERVED,
    [143] = KEY_RESERVED,
    [144] = KEY_RESERVED,
    [145] = KEY_RESERVED,
    [146] = KEY_RESERVED,
    [147] = KEY_RESERVED,
    [148] = KEY_RESERVED,
    [149] = KEY_RESERVED,
    [150] = KEY_RESERVED,
    [151] = KEY_RESERVED,
    [152] = KEY_RESERVED,
    [153] = KEY_RESERVED,
    [154] = KEY_RESERVED,
    [155] = KEY_RESERVED,
    [156] = KEY_RESERVED,
    [157] = KEY_RESERVED,
    [158] = KEY_RESERVED,
    [159] = KEY_RESERVED,
    [160] = KEY_RESERVED,
    [161] = KEY_RESERVED,
    [162] = KEY_RESERVED,
    [163] = KEY_RESERVED,
    [164] = KEY_RESERVED,
    [165] = KEY_RESERVED,
    [166] = KEY_RESERVED,
    [167] = KEY_RESERVED,
    [168] = KEY_RESERVED,
    [169] = KEY_RESERVED,
    [170] = KEY_RESERVED,
    [171] = KEY_RESERVED,
    [172] = KEY_RESERVED,
    [173] = KEY_RESERVED,
    [174] = KEY_RESERVED,
    [175] = KEY_RESERVED,
    [176] = KEY_RESERVED,
    [177] = KEY_RESERVED,
    [178] = KEY_RESERVED,
    [179] = KEY_RESERVED,
    [180] = KEY_RESERVED,
    [181] = KEY_RESERVED,
    [182] = KEY_RESERVED,
    [183] = KEY_RESERVED,
    [184] = KEY_RESERVED,
    [185] = KEY_RESERVED,
    [186] = KEY_RESERVED,
    [187] = KEY_RESERVED,
    [188] = KEY_RESERVED,
    [189] = KEY_RESERVED,
    [190] = KEY_RESERVED,
    [191] = KEY_RESERVED,
    [192] = KEY_RESERVED,
    [193] = KEY_RESERVED,
    [194] = KEY_RESERVED,
    [195] = KEY_RESERVED,
    [196] = KEY_RESERVED,
    [197] = KEY_RESERVED,
    [198] = KEY_RESERVED,
    [199] = KEY_RESERVED,
    [200] = KEY_RESERVED,
    [201] = KEY_RESERVED,
    [202] = KEY_RESERVED,
    [203] = KEY_RESERVED,
    [204] = KEY_RESERVED,
    [205] = KEY_RESERVED,
    [206] = KEY_RESERVED,
    [207] = KEY_RESERVED,
    [208] = KEY_RESERVED,
    [209] = KEY_RESERVED,
    [210] = KEY_RESERVED,
    [211] = KEY_RESERVED,
    [212] = KEY_RESERVED,
    [213] = KEY_RESERVED,
    [214] = KEY_RESERVED,
    [215] = KEY_RESERVED,
    [216] = KEY_RESERVED,
    [217] = KEY_RESERVED,
    [218] = KEY_RESERVED,
    [219] = KEY_RESERVED,
    [220] = KEY_RESERVED,
    [221] = KEY_RESERVED,
    [222] = KEY_RESERVED,
    [223] = KEY_RESERVED,
    [224] = KEY_RESERVED,
    [225] = KEY_RESERVED,
    [226] = KEY_RESERVED,
    [227] = KEY_RESERVED,
    [228] = KEY_RESERVED,
    [229] = KEY_RESERVED,
    [230] = KEY_RESERVED,
    [231] = KEY_RESERVED,
    [232] = KEY_RESERVED,
    [233] = KEY_RESERVED,
    [234] = KEY_RESERVED,
    [235] = KEY_RESERVED,
    [236] = KEY_RESERVED,
    [237] = KEY_RESERVED,
    [238] = KEY_RESERVED,
    [239] = KEY_RESERVED,
    [240] = KEY_RESERVED,
    [241] = KEY_RESERVED,
    [242] = KEY_RESERVED,
    [243] = KEY_RESERVED,
    [244] = KEY_RESERVED,
    [245] = KEY_RESERVED,
    [246] = KEY_RESERVED,
    [247] = KEY_RESERVED,
    [248] = KEY_RESERVED,
    [249] = KEY_RESERVED,
    [250] = KEY_RESERVED,
    [251] = KEY_RESERVED,
    [252] = KEY_RESERVED,
    [253] = KEY_RESERVED,
    [254] = KEY_RESERVED,
    [255] = KEY_RESERVED,
};

static const unsigned short ft_scancodes_ext[256] = {
    [0] = KEY_RESERVED,
    [1] = KEY_RESERVED,
    [2] = KEY_RESERVED,
    [3] = KEY_RESERVED,
    [4] = KEY_RESERVED,
    [5] = KEY_RESERVED,
    [6] = KEY_RESERVED,
    [7] = KEY_RESERVED,
    [8] = KEY_RESERVED,
    [9] = KEY_RESERVED,
    [10] = KEY_RESERVED,
    [11] = KEY_RESERVED,
    [12] = KEY_RESERVED,
    [13] = KEY_RESERVED,
    [14] = KEY_RESERVED,
    [15] = KEY_RESERVED,
    [16] = KEY_RESERVED,
    [17] = KEY_RESERVED,
    [18] = KEY_RESERVED,
    [19] = KEY_RESERVED,
    [20] = KEY_RESERVED,
    [21] = KEY_RESERVED,
    [22] = KEY_RESERVED,
    [23] = KEY_RESERVED,
    [24] = KEY_RESERVED,
    [25] = KEY_RESERVED,
    [26] = KEY_RESERVED,
    [27] = KEY_RESERVED,
    [28] = KEY_KPENTER,
    [29] = KEY_RIGHTCTRL,
    [30] = KEY_RESERVED,
    [31] = KEY_RESERVED,
    [32] = KEY_RESERVED,
    [33] = KEY_RESERVED,
    [34] = KEY_RESERVED,
    [35] = KEY_RESERVED,
    [36] = KEY_RESERVED,
    [37] = KEY_RESERVED,
    [38] = KEY_RESERVED,
    [39] = KEY_RESERVED,
    [40] = KEY_RESERVED,
    [41] = KEY_RESERVED,
    [42] = KEY_RESERVED,
    [43] = KEY_RESERVED,
    [44] = KEY_RESERVED,
    [45] = KEY_RESERVED,
    [46] = KEY_RESERVED,
    [47] = KEY_RESERVED,
    [48] = KEY_RESERVED,
    [49] = KEY_RESERVED,
    [50] = KEY_RESERVED,
    [51] = KEY_RESERVED,
    [52] = KEY_RESERVED,
    [53] = KEY_KPSLASH,
    [54] = KEY_RESERVED,
    [55] = KEY_RESERVED,
    [56] = KEY_RIGHTALT,
    [57] = KEY_RESERVED,
    [58] = KEY_RESERVED,
    [59] = KEY_RESERVED,
    [60] = KEY_RESERVED,
    [61] = KEY_RESERVED,
    [62] = KEY_RESERVED,
    [63] = KEY_RESERVED,
    [64] = KEY_RESERVED,
    [65] = KEY_RESERVED,
    [66] = KEY_RESERVED,
    [67] = KEY_RESERVED,
    [68] = KEY_RESERVED,
    [69] = KEY_RESERVED,
    [70] = KEY_RESERVED,
    [71] = KEY_HOME,
    [72] = KEY_UP,
    [73] = KEY_PAGEUP,
    [74] = KEY_RESERVED,
    [75] = KEY_LEFT,
    [76] = KEY_RESERVED,
    [77] = KEY_RIGHT,
    [78] = KEY_RESERVED,
    [79] = KEY_END,
    [80] = KEY_DOWN,
    [81] = KEY_PAGEDOWN,
    [82] = KEY_INSERT,
    [83] = KEY_DELETE,
    [84] = KEY_RESERVED,
    [85] = KEY_RESERVED,
    [86] = KEY_RESERVED,
    [87] = KEY_RESERVED,
    [88] = KEY_RESERVED,
    [89] = KEY_RESERVED,
    [90] = KEY_RESERVED,
    [91] = KEY_LEFTMETA,
    [92] = KEY_RIGHTMETA,
    [93] = KEY_COMPOSE,
    [94] = KEY_RESERVED,
    [95] = KEY_RESERVED,
    [96] = KEY_RESERVED,
    [97] = KEY_RESERVED,
    [98] = KEY_RESERVED,
    [99] = KEY_RESERVED,
    [100] = KEY_RESERVED,
    [101] = KEY_RESERVED,
    [102] = KEY_RESERVED,
    [103] = KEY_RESERVED,
    [104] = KEY_RESERVED,
    [105] = KEY_RESERVED,
    [106] = KEY_RESERVED,
    [107] = KEY_RESERVED,
    [108] = KEY_RESERVED,
    [109] = KEY_RESERVED,
    [110] = KEY_RESERVED,
    [111] = KEY_RESERVED,
    [112] = KEY_RESERVED,
    [113] = KEY_RESERVED,
    [114] = KEY_RESERVED,
    [115] = KEY_RESERVED,
    [116] = KEY_RESERVED,
    [117] = KEY_RESERVED,
    [118] = KEY_RESERVED,
    [119] = KEY_RESERVED,
    [120] = KEY_RESERVED,
    [121] = KEY_RESERVED,
    [122] = KEY_RESERVED,
    [123] = KEY_RESERVED,
    [124] = KEY_RESERVED,
    [125] = KEY_RESERVED,
    [126] = KEY_RESERVED,
    [127] = KEY_RESERVED,
    [128] = KEY_RESERVED,
    [129] = KEY_RESERVED,
    [130] = KEY_RESERVED,
    [131] = KEY_RESERVED,
    [132] = KEY_RESERVED,
    [133] = KEY_RESERVED,
    [134] = KEY_RESERVED,
    [135] = KEY_RESERVED,
    [136] = KEY_RESERVED,
    [137] = KEY_RESERVED,
    [138] = KEY_RESERVED,
    [139] = KEY_RESERVED,
    [140] = KEY_RESERVED,
    [141] = KEY_RESERVED,
    [142] = KEY_RESERVED,
    [143] = KEY_RESERVED,
    [144] = KEY_RESERVED,
    [145] = KEY_RESERVED,
    [146] = KEY_RESERVED,
    [147] = KEY_RESERVED,
    [148] = KEY_RESERVED,
    [149] = KEY_RESERVED,
    [150] = KEY_RESERVED,
    [151] = KEY_RESERVED,
    [152] = KEY_RESERVED,
    [153] = KEY_RESERVED,
    [154] = KEY_RESERVED,
    [155] = KEY_RESERVED,
    [156] = KEY_RESERVED,
    [157] = KEY_RESERVED,
    [158] = KEY_RESERVED,
    [159] = KEY_RESERVED,
    [160] = KEY_RESERVED,
    [161] = KEY_RESERVED,
    [162] = KEY_RESERVED,
    [163] = KEY_RESERVED,
    [164] = KEY_RESERVED,
    [165] = KEY_RESERVED,
    [166] = KEY_RESERVED,
    [167] = KEY_RESERVED,
    [168] = KEY_RESERVED,
    [169] = KEY_RESERVED,
    [170] = KEY_RESERVED,
    [171] = KEY_RESERVED,
    [172] = KEY_RESERVED,
    [173] = KEY_RESERVED,
    [174] = KEY_RESERVED,
    [175] = KEY_RESERVED,
    [176] = KEY_RESERVED,
    [177] = KEY_RESERVED,
    [178] = KEY_RESERVED,
    [179] = KEY_RESERVED,
    [180] = KEY_RESERVED,
    [181] = KEY_RESERVED,
    [182] = KEY_RESERVED,
    [183] = KEY_RESERVED,
    [184] = KEY_RESERVED,
    [185] = KEY_RESERVED,
    [186] = KEY_RESERVED,
    [187] = KEY_RESERVED,
    [188] = KEY_RESERVED,
    [189] = KEY_RESERVED,
    [190] = KEY_RESERVED,
    [191] = KEY_RESERVED,
    [192] = KEY_RESERVED,
    [193] = KEY_RESERVED,
    [194] = KEY_RESERVED,
    [195] = KEY_RESERVED,
    [196] = KEY_RESERVED,
    [197] = KEY_RESERVED,
    [198] = KEY_RESERVED,
    [199] = KEY_RESERVED,
    [200] = KEY_RESERVED,
    [201] = KEY_RESERVED,
    [202] = KEY_RESERVED,
    [203] = KEY_RESERVED,
    [204] = KEY_RESERVED,
    [205] = KEY_RESERVED,
    [206] = KEY_RESERVED,
    [207] = KEY_RESERVED,
    [208] = KEY_RESERVED,
    [209] = KEY_RESERVED,
    [210] = KEY_RESERVED,
    [211] = KEY_RESERVED,
    [212] = KEY_RESERVED,
    [213] = KEY_RESERVED,
    [214] = KEY_RESERVED,
    [215] = KEY_RESERVED,
    [216] = KEY_RESERVED,
    [217] = KEY_RESERVED,
    [218] = KEY_RESERVED,
    [219] = KEY_RESERVED,
    [220] = KEY_RESERVED,
    [221] = KEY_RESERVED,
    [222] = KEY_RESERVED,
    [223] = KEY_RESERVED,
    [224] = KEY_RESERVED,
    [225] = KEY_RESERVED,
    [226] = KEY_RESERVED,
    [227] = KEY_RESERVED,
    [228] = KEY_RESERVED,
    [229] = KEY_RESERVED,
    [230] = KEY_RESERVED,
    [231] = KEY_RESERVED,
    [232] = KEY_RESERVED,
    [233] = KEY_RESERVED,
    [234] = KEY_RESERVED,
    [235] = KEY_RESERVED,
    [236] = KEY_RESERVED,
    [237] = KEY_RESERVED,
    [238] = KEY_RESERVED,
    [239] = KEY_RESERVED,
    [240] = KEY_RESERVED,
    [241] = KEY_RESERVED,
    [242] = KEY_RESERVED,
    [243] = KEY_RESERVED,
    [244] = KEY_RESERVED,
    [245] = KEY_RESERVED,he devices. is it bad ?
    [246] = KEY_RESERVED,
    [247] = KEY_RESERVED,
    [248] = KEY_RESERVED,
    [249] = KEY_RESERVED,
    [250] = KEY_RESERVED,
    [251] = KEY_RESERVED,
    [252] = KEY_RESERVED,
    [253] = KEY_RESERVED,
    [254] = KEY_RESERVED,
    [255] = KEY_RESERVED,
};
// [MAP_END]

struct s_device {
	int		irq;
	void __iomem	*regs;
};

static struct input_dev	*ft_keyboard;

static struct s_device	my_dev;

static int	is_extended = 0;

static irqreturn_t	kdb_irq_handler(int irq, void *dev_id)
{
	unsigned char	scancode = inb(0x60);
	unsigned short	table = is_extended ? ft_scancodes_ext : ft_scancodes_std;

	if (scancode == 0xE0) {
		is_extended = 1;
		return IRQ_HANDLED;
	}
	if (is_extended)
		is_extended = 0;
	input_report_key(ft_keyboard, table[scancode & 0x7F], !(scancode & 0x80));
	input_sync(ft_keyboard);
	return IRQ_HANDLED;
}

#define MAX_KEY 0x58

static int __init hello_1_init(void)
{
	pr_info("loading ft_atkbd\n");

	int	ret = request_irq(KEYB_IRQ, kdb_irq_handler, IRQF_SHARED,
				  DEV_NAME, (void *)(&my_dev));
	if (ret) {
		pr_err("Failed to reserve IRQ");
		return ret;
	}
	ft_keyboard = input_allocate_device();
	if (!ft_keyboard) {
		printk(KERN_ERR "ft_atkbd.c: Not enough memory\n");
		ret = -ENOMEM;
		goto err_free_irq;
	}
	set_bit(EV_KEY, ft_keyboard->evbit);
	set_bit(EV_REP, ft_keyboard->evbit);
	for (int i = 0; i <= MAX_KEY; i++)
		set_bit(i, ft_keyboard->keybit);
	ret = input_register_device(ft_keyboard);
	if (ret) {
		printk(KERN_ERR "ft_atkbd.c: Failed to register device\n");
		goto err_free_dev;
	}
	ft_keyboard->name = "ft_keyboard";
	ft_keyboard->phys = "ft_keyb/input0";
	ft_keyboard->id.bustype = BUS_ISA;
	ft_keyboard->id.vendor = 0x0001;
	ft_keyboard->id.product = 0x0001;
	ft_keyboard->id.version = 0x0100;
	return 0;
err_free_dev:
	input_free_device(ft_keyboard);
err_free_irq:
	free_irq(KEYB_IRQ, (void *)(&my_dev));
	return ret;
}

static void __exit hello_1_exit(void)
{
	input_unregister_device(ft_keyboard);
	free_irq(KEYB_IRQ, (void *)(&my_dev));
	pr_info("unloading ft_atkbd\n");
}

late_initcall(hello_1_init);
module_exit(hello_1_exit);

MODULE_LICENSE("GPL");
